// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBblx8cP8L5H2k9l2wflCtXMg7up22Y8xA',
    appId: '1:16056185865:web:9adb55d65fd6288cb1f4d8',
    messagingSenderId: '16056185865',
    projectId: 'talentx-458f4',
    authDomain: 'talentx-458f4.firebaseapp.com',
    storageBucket: 'talentx-458f4.firebasestorage.app',
    measurementId: 'G-CGJLQJ3Q02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeiIQ0nIESO3Gr3RUj6C80mWdVnIS748A',
    appId: '1:16056185865:android:ba750fa224f9ec54b1f4d8',
    messagingSenderId: '16056185865',
    projectId: 'talentx-458f4',
    storageBucket: 'talentx-458f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsv7y3JuI5wuQSmeXHFYtTvrq4mwMnM48',
    appId: '1:16056185865:ios:d40d1681f789059bb1f4d8',
    messagingSenderId: '16056185865',
    projectId: 'talentx-458f4',
    storageBucket: 'talentx-458f4.firebasestorage.app',
    iosBundleId: 'com.koralogix.talentx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsv7y3JuI5wuQSmeXHFYtTvrq4mwMnM48',
    appId: '1:16056185865:ios:d40d1681f789059bb1f4d8',
    messagingSenderId: '16056185865',
    projectId: 'talentx-458f4',
    storageBucket: 'talentx-458f4.firebasestorage.app',
    iosBundleId: 'com.koralogix.talentx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBblx8cP8L5H2k9l2wflCtXMg7up22Y8xA',
    appId: '1:16056185865:web:11f91aa0250d060db1f4d8',
    messagingSenderId: '16056185865',
    projectId: 'talentx-458f4',
    authDomain: 'talentx-458f4.firebaseapp.com',
    storageBucket: 'talentx-458f4.firebasestorage.app',
    measurementId: 'G-L7TXWFT41J',
  );
}
